name: Minishell Core Test

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install valgrind
      run: sudo apt install valgrind
    - name: make
      run: make      
    - name: test command exit
      run: |
        valgrind --leak-check=full -s ./minishell << EOF
        exit
        EOF
        [[ $? -eq 0 ]] && echo "OK" || echo "KO"
    - name: test command exit -2
      run: |
        set +e
        valgrind --leak-check=full -s ./minishell << EOF
        exit -2
        EOF
        EXIT_CODE=$?
        set -e
        if [[ $EXIT_CODE -eq 254 ]]; then
          echo "OK"
        else
          echo "KO"
          exit 0
        fi
    - name: test command exit a
      run: |
        set +e
        valgrind --leak-check=full -s ./minishell << EOF
        exit -2
        EOF
        EXIT_CODE=$?
        set -e
        if [[ $EXIT_CODE -eq 2 ]]; then
          echo "OK"
        else
          echo "KO"
          exit 0
        fi
