name: Minishell Core Test

on:
  pull_request:
    branches: [ "main" ]

  workflow_call:
    inputs:
      command:
        description: 'Command to pass to minishell'
        default: 'exit'
        required: yes
        type: string

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install norminette
      run: pip install norminette
    - name: review norminette
      run: norminette      
    - name: make
      run: make
    - name: test command
      run: |
        ./minishell << EOF
        ${{ inputs.command }}
        EOF
