name: Minishell Core Test

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install norminette
      run: pip install norminette
    - name: review norminette
      run: norminette      
    - name: make
      run: make
    - name: test command
      run: |
        valgrind --leak-check=full -s ./minishell << EOF
        exit
        EOF
